// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: neuronai.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AIService_ProcessChat_FullMethodName      = "/neuronai.AIService/ProcessChat"
	AIService_ProcessStream_FullMethodName    = "/neuronai.AIService/ProcessStream"
	AIService_ExecuteSwarmTask_FullMethodName = "/neuronai.AIService/ExecuteSwarmTask"
)

// AIServiceClient is the client API for AIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Services
type AIServiceClient interface {
	ProcessChat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error)
	ProcessStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamRequest, StreamResponse], error)
	ExecuteSwarmTask(ctx context.Context, in *SwarmTask, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SwarmState], error)
}

type aIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAIServiceClient(cc grpc.ClientConnInterface) AIServiceClient {
	return &aIServiceClient{cc}
}

func (c *aIServiceClient) ProcessChat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatResponse)
	err := c.cc.Invoke(ctx, AIService_ProcessChat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) ProcessStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamRequest, StreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AIService_ServiceDesc.Streams[0], AIService_ProcessStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamRequest, StreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AIService_ProcessStreamClient = grpc.BidiStreamingClient[StreamRequest, StreamResponse]

func (c *aIServiceClient) ExecuteSwarmTask(ctx context.Context, in *SwarmTask, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SwarmState], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AIService_ServiceDesc.Streams[1], AIService_ExecuteSwarmTask_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SwarmTask, SwarmState]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AIService_ExecuteSwarmTaskClient = grpc.ServerStreamingClient[SwarmState]

// AIServiceServer is the server API for AIService service.
// All implementations must embed UnimplementedAIServiceServer
// for forward compatibility.
//
// Services
type AIServiceServer interface {
	ProcessChat(context.Context, *ChatRequest) (*ChatResponse, error)
	ProcessStream(grpc.BidiStreamingServer[StreamRequest, StreamResponse]) error
	ExecuteSwarmTask(*SwarmTask, grpc.ServerStreamingServer[SwarmState]) error
	mustEmbedUnimplementedAIServiceServer()
}

// UnimplementedAIServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAIServiceServer struct{}

func (UnimplementedAIServiceServer) ProcessChat(context.Context, *ChatRequest) (*ChatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessChat not implemented")
}
func (UnimplementedAIServiceServer) ProcessStream(grpc.BidiStreamingServer[StreamRequest, StreamResponse]) error {
	return status.Error(codes.Unimplemented, "method ProcessStream not implemented")
}
func (UnimplementedAIServiceServer) ExecuteSwarmTask(*SwarmTask, grpc.ServerStreamingServer[SwarmState]) error {
	return status.Error(codes.Unimplemented, "method ExecuteSwarmTask not implemented")
}
func (UnimplementedAIServiceServer) mustEmbedUnimplementedAIServiceServer() {}
func (UnimplementedAIServiceServer) testEmbeddedByValue()                   {}

// UnsafeAIServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIServiceServer will
// result in compilation errors.
type UnsafeAIServiceServer interface {
	mustEmbedUnimplementedAIServiceServer()
}

func RegisterAIServiceServer(s grpc.ServiceRegistrar, srv AIServiceServer) {
	// If the following call panics, it indicates UnimplementedAIServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AIService_ServiceDesc, srv)
}

func _AIService_ProcessChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).ProcessChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_ProcessChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).ProcessChat(ctx, req.(*ChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_ProcessStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AIServiceServer).ProcessStream(&grpc.GenericServerStream[StreamRequest, StreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AIService_ProcessStreamServer = grpc.BidiStreamingServer[StreamRequest, StreamResponse]

func _AIService_ExecuteSwarmTask_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SwarmTask)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AIServiceServer).ExecuteSwarmTask(m, &grpc.GenericServerStream[SwarmTask, SwarmState]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AIService_ExecuteSwarmTaskServer = grpc.ServerStreamingServer[SwarmState]

// AIService_ServiceDesc is the grpc.ServiceDesc for AIService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "neuronai.AIService",
	HandlerType: (*AIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessChat",
			Handler:    _AIService_ProcessChat_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ProcessStream",
			Handler:       _AIService_ProcessStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ExecuteSwarmTask",
			Handler:       _AIService_ExecuteSwarmTask_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "neuronai.proto",
}

const (
	SwarmOrchestrator_RegisterAgent_FullMethodName    = "/neuronai.SwarmOrchestrator/RegisterAgent"
	SwarmOrchestrator_UpdateSwarmState_FullMethodName = "/neuronai.SwarmOrchestrator/UpdateSwarmState"
	SwarmOrchestrator_GetSwarmState_FullMethodName    = "/neuronai.SwarmOrchestrator/GetSwarmState"
)

// SwarmOrchestratorClient is the client API for SwarmOrchestrator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SwarmOrchestratorClient interface {
	RegisterAgent(ctx context.Context, in *AgentState, opts ...grpc.CallOption) (*AgentState, error)
	UpdateSwarmState(ctx context.Context, in *SwarmState, opts ...grpc.CallOption) (*SwarmState, error)
	GetSwarmState(ctx context.Context, in *GetSwarmStateRequest, opts ...grpc.CallOption) (*SwarmState, error)
}

type swarmOrchestratorClient struct {
	cc grpc.ClientConnInterface
}

func NewSwarmOrchestratorClient(cc grpc.ClientConnInterface) SwarmOrchestratorClient {
	return &swarmOrchestratorClient{cc}
}

func (c *swarmOrchestratorClient) RegisterAgent(ctx context.Context, in *AgentState, opts ...grpc.CallOption) (*AgentState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentState)
	err := c.cc.Invoke(ctx, SwarmOrchestrator_RegisterAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swarmOrchestratorClient) UpdateSwarmState(ctx context.Context, in *SwarmState, opts ...grpc.CallOption) (*SwarmState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SwarmState)
	err := c.cc.Invoke(ctx, SwarmOrchestrator_UpdateSwarmState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swarmOrchestratorClient) GetSwarmState(ctx context.Context, in *GetSwarmStateRequest, opts ...grpc.CallOption) (*SwarmState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SwarmState)
	err := c.cc.Invoke(ctx, SwarmOrchestrator_GetSwarmState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SwarmOrchestratorServer is the server API for SwarmOrchestrator service.
// All implementations must embed UnimplementedSwarmOrchestratorServer
// for forward compatibility.
type SwarmOrchestratorServer interface {
	RegisterAgent(context.Context, *AgentState) (*AgentState, error)
	UpdateSwarmState(context.Context, *SwarmState) (*SwarmState, error)
	GetSwarmState(context.Context, *GetSwarmStateRequest) (*SwarmState, error)
	mustEmbedUnimplementedSwarmOrchestratorServer()
}

// UnimplementedSwarmOrchestratorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSwarmOrchestratorServer struct{}

func (UnimplementedSwarmOrchestratorServer) RegisterAgent(context.Context, *AgentState) (*AgentState, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterAgent not implemented")
}
func (UnimplementedSwarmOrchestratorServer) UpdateSwarmState(context.Context, *SwarmState) (*SwarmState, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSwarmState not implemented")
}
func (UnimplementedSwarmOrchestratorServer) GetSwarmState(context.Context, *GetSwarmStateRequest) (*SwarmState, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSwarmState not implemented")
}
func (UnimplementedSwarmOrchestratorServer) mustEmbedUnimplementedSwarmOrchestratorServer() {}
func (UnimplementedSwarmOrchestratorServer) testEmbeddedByValue()                           {}

// UnsafeSwarmOrchestratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SwarmOrchestratorServer will
// result in compilation errors.
type UnsafeSwarmOrchestratorServer interface {
	mustEmbedUnimplementedSwarmOrchestratorServer()
}

func RegisterSwarmOrchestratorServer(s grpc.ServiceRegistrar, srv SwarmOrchestratorServer) {
	// If the following call panics, it indicates UnimplementedSwarmOrchestratorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SwarmOrchestrator_ServiceDesc, srv)
}

func _SwarmOrchestrator_RegisterAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentState)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwarmOrchestratorServer).RegisterAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwarmOrchestrator_RegisterAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwarmOrchestratorServer).RegisterAgent(ctx, req.(*AgentState))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwarmOrchestrator_UpdateSwarmState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SwarmState)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwarmOrchestratorServer).UpdateSwarmState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwarmOrchestrator_UpdateSwarmState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwarmOrchestratorServer).UpdateSwarmState(ctx, req.(*SwarmState))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwarmOrchestrator_GetSwarmState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSwarmStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwarmOrchestratorServer).GetSwarmState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwarmOrchestrator_GetSwarmState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwarmOrchestratorServer).GetSwarmState(ctx, req.(*GetSwarmStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SwarmOrchestrator_ServiceDesc is the grpc.ServiceDesc for SwarmOrchestrator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SwarmOrchestrator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "neuronai.SwarmOrchestrator",
	HandlerType: (*SwarmOrchestratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterAgent",
			Handler:    _SwarmOrchestrator_RegisterAgent_Handler,
		},
		{
			MethodName: "UpdateSwarmState",
			Handler:    _SwarmOrchestrator_UpdateSwarmState_Handler,
		},
		{
			MethodName: "GetSwarmState",
			Handler:    _SwarmOrchestrator_GetSwarmState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "neuronai.proto",
}
