// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: neuronai.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Agent message types
type AgentType int32

const (
	AgentType_AGENT_TYPE_UNSPECIFIED  AgentType = 0
	AgentType_AGENT_TYPE_ORCHESTRATOR AgentType = 1
	AgentType_AGENT_TYPE_RESEARCHER   AgentType = 2
	AgentType_AGENT_TYPE_WRITER       AgentType = 3
	AgentType_AGENT_TYPE_CODE         AgentType = 4
	AgentType_AGENT_TYPE_IMAGE        AgentType = 5
	AgentType_AGENT_TYPE_VIDEO        AgentType = 6
)

// Enum value maps for AgentType.
var (
	AgentType_name = map[int32]string{
		0: "AGENT_TYPE_UNSPECIFIED",
		1: "AGENT_TYPE_ORCHESTRATOR",
		2: "AGENT_TYPE_RESEARCHER",
		3: "AGENT_TYPE_WRITER",
		4: "AGENT_TYPE_CODE",
		5: "AGENT_TYPE_IMAGE",
		6: "AGENT_TYPE_VIDEO",
	}
	AgentType_value = map[string]int32{
		"AGENT_TYPE_UNSPECIFIED":  0,
		"AGENT_TYPE_ORCHESTRATOR": 1,
		"AGENT_TYPE_RESEARCHER":   2,
		"AGENT_TYPE_WRITER":       3,
		"AGENT_TYPE_CODE":         4,
		"AGENT_TYPE_IMAGE":        5,
		"AGENT_TYPE_VIDEO":        6,
	}
)

func (x AgentType) Enum() *AgentType {
	p := new(AgentType)
	*p = x
	return p
}

func (x AgentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentType) Descriptor() protoreflect.EnumDescriptor {
	return file_neuronai_proto_enumTypes[0].Descriptor()
}

func (AgentType) Type() protoreflect.EnumType {
	return &file_neuronai_proto_enumTypes[0]
}

func (x AgentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentType.Descriptor instead.
func (AgentType) EnumDescriptor() ([]byte, []int) {
	return file_neuronai_proto_rawDescGZIP(), []int{0}
}

type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNSPECIFIED MessageType = 0
	MessageType_MESSAGE_TYPE_TEXT        MessageType = 1
	MessageType_MESSAGE_TYPE_IMAGE       MessageType = 2
	MessageType_MESSAGE_TYPE_VIDEO       MessageType = 3
	MessageType_MESSAGE_TYPE_CODE        MessageType = 4
	MessageType_MESSAGE_TYPE_TOOL_CALL   MessageType = 5
	MessageType_MESSAGE_TYPE_TOOL_RESULT MessageType = 6
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MESSAGE_TYPE_UNSPECIFIED",
		1: "MESSAGE_TYPE_TEXT",
		2: "MESSAGE_TYPE_IMAGE",
		3: "MESSAGE_TYPE_VIDEO",
		4: "MESSAGE_TYPE_CODE",
		5: "MESSAGE_TYPE_TOOL_CALL",
		6: "MESSAGE_TYPE_TOOL_RESULT",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNSPECIFIED": 0,
		"MESSAGE_TYPE_TEXT":        1,
		"MESSAGE_TYPE_IMAGE":       2,
		"MESSAGE_TYPE_VIDEO":       3,
		"MESSAGE_TYPE_CODE":        4,
		"MESSAGE_TYPE_TOOL_CALL":   5,
		"MESSAGE_TYPE_TOOL_RESULT": 6,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_neuronai_proto_enumTypes[1].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_neuronai_proto_enumTypes[1]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_neuronai_proto_rawDescGZIP(), []int{1}
}

type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_UNSPECIFIED TaskStatus = 0
	TaskStatus_TASK_STATUS_PENDING     TaskStatus = 1
	TaskStatus_TASK_STATUS_IN_PROGRESS TaskStatus = 2
	TaskStatus_TASK_STATUS_COMPLETED   TaskStatus = 3
	TaskStatus_TASK_STATUS_FAILED      TaskStatus = 4
	TaskStatus_TASK_STATUS_CANCELLED   TaskStatus = 5
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_STATUS_UNSPECIFIED",
		1: "TASK_STATUS_PENDING",
		2: "TASK_STATUS_IN_PROGRESS",
		3: "TASK_STATUS_COMPLETED",
		4: "TASK_STATUS_FAILED",
		5: "TASK_STATUS_CANCELLED",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_UNSPECIFIED": 0,
		"TASK_STATUS_PENDING":     1,
		"TASK_STATUS_IN_PROGRESS": 2,
		"TASK_STATUS_COMPLETED":   3,
		"TASK_STATUS_FAILED":      4,
		"TASK_STATUS_CANCELLED":   5,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_neuronai_proto_enumTypes[2].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_neuronai_proto_enumTypes[2]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_neuronai_proto_rawDescGZIP(), []int{2}
}

// Request/Response messages
type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	MessageType   MessageType            `protobuf:"varint,4,opt,name=message_type,json=messageType,proto3,enum=neuronai.MessageType" json:"message_type,omitempty"`
	Attachments   []*Attachment          `protobuf:"bytes,5,rep,name=attachments,proto3" json:"attachments,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_neuronai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neuronai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_neuronai_proto_rawDescGZIP(), []int{0}
}

func (x *ChatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ChatRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatRequest) GetMessageType() MessageType {
	if x != nil {
		return x.MessageType
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

func (x *ChatRequest) GetAttachments() []*Attachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *ChatRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	MessageType   MessageType            `protobuf:"varint,4,opt,name=message_type,json=messageType,proto3,enum=neuronai.MessageType" json:"message_type,omitempty"`
	AgentType     AgentType              `protobuf:"varint,5,opt,name=agent_type,json=agentType,proto3,enum=neuronai.AgentType" json:"agent_type,omitempty"`
	Status        TaskStatus             `protobuf:"varint,6,opt,name=status,proto3,enum=neuronai.TaskStatus" json:"status,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	IsFinal       bool                   `protobuf:"varint,8,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	ToolCalls     []*ToolCall            `protobuf:"bytes,9,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_neuronai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neuronai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_neuronai_proto_rawDescGZIP(), []int{1}
}

func (x *ChatResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ChatResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatResponse) GetMessageType() MessageType {
	if x != nil {
		return x.MessageType
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

func (x *ChatResponse) GetAgentType() AgentType {
	if x != nil {
		return x.AgentType
	}
	return AgentType_AGENT_TYPE_UNSPECIFIED
}

func (x *ChatResponse) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *ChatResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ChatResponse) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

func (x *ChatResponse) GetToolCalls() []*ToolCall {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

type Attachment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	MimeType      string                 `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Url           string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attachment) Reset() {
	*x = Attachment{}
	mi := &file_neuronai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attachment) ProtoMessage() {}

func (x *Attachment) ProtoReflect() protoreflect.Message {
	mi := &file_neuronai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attachment.ProtoReflect.Descriptor instead.
func (*Attachment) Descriptor() ([]byte, []int) {
	return file_neuronai_proto_rawDescGZIP(), []int{2}
}

func (x *Attachment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Attachment) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Attachment) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *Attachment) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Attachment) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ToolCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Arguments     string                 `protobuf:"bytes,3,opt,name=arguments,proto3" json:"arguments,omitempty"`
	Result        string                 `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_neuronai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_neuronai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_neuronai_proto_rawDescGZIP(), []int{3}
}

func (x *ToolCall) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolCall) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolCall) GetArguments() string {
	if x != nil {
		return x.Arguments
	}
	return ""
}

func (x *ToolCall) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

// Swarm orchestration
type SwarmTask struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	SessionId      string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	RequiredAgents []string               `protobuf:"bytes,4,rep,name=required_agents,json=requiredAgents,proto3" json:"required_agents,omitempty"`
	Context        map[string]string      `protobuf:"bytes,5,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Status         TaskStatus             `protobuf:"varint,6,opt,name=status,proto3,enum=neuronai.TaskStatus" json:"status,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SwarmTask) Reset() {
	*x = SwarmTask{}
	mi := &file_neuronai_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwarmTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwarmTask) ProtoMessage() {}

func (x *SwarmTask) ProtoReflect() protoreflect.Message {
	mi := &file_neuronai_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwarmTask.ProtoReflect.Descriptor instead.
func (*SwarmTask) Descriptor() ([]byte, []int) {
	return file_neuronai_proto_rawDescGZIP(), []int{4}
}

func (x *SwarmTask) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *SwarmTask) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SwarmTask) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SwarmTask) GetRequiredAgents() []string {
	if x != nil {
		return x.RequiredAgents
	}
	return nil
}

func (x *SwarmTask) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *SwarmTask) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *SwarmTask) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SwarmTask) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type SwarmState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Agents        []*AgentState          `protobuf:"bytes,2,rep,name=agents,proto3" json:"agents,omitempty"`
	CurrentTask   *SwarmTask             `protobuf:"bytes,3,opt,name=current_task,json=currentTask,proto3" json:"current_task,omitempty"`
	SharedContext map[string]string      `protobuf:"bytes,4,rep,name=shared_context,json=sharedContext,proto3" json:"shared_context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwarmState) Reset() {
	*x = SwarmState{}
	mi := &file_neuronai_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwarmState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwarmState) ProtoMessage() {}

func (x *SwarmState) ProtoReflect() protoreflect.Message {
	mi := &file_neuronai_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwarmState.ProtoReflect.Descriptor instead.
func (*SwarmState) Descriptor() ([]byte, []int) {
	return file_neuronai_proto_rawDescGZIP(), []int{5}
}

func (x *SwarmState) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SwarmState) GetAgents() []*AgentState {
	if x != nil {
		return x.Agents
	}
	return nil
}

func (x *SwarmState) GetCurrentTask() *SwarmTask {
	if x != nil {
		return x.CurrentTask
	}
	return nil
}

func (x *SwarmState) GetSharedContext() map[string]string {
	if x != nil {
		return x.SharedContext
	}
	return nil
}

type AgentState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentType     AgentType              `protobuf:"varint,2,opt,name=agent_type,json=agentType,proto3,enum=neuronai.AgentType" json:"agent_type,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	CurrentTask   string                 `protobuf:"bytes,4,opt,name=current_task,json=currentTask,proto3" json:"current_task,omitempty"`
	Memory        map[string]string      `protobuf:"bytes,5,rep,name=memory,proto3" json:"memory,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentState) Reset() {
	*x = AgentState{}
	mi := &file_neuronai_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentState) ProtoMessage() {}

func (x *AgentState) ProtoReflect() protoreflect.Message {
	mi := &file_neuronai_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentState.ProtoReflect.Descriptor instead.
func (*AgentState) Descriptor() ([]byte, []int) {
	return file_neuronai_proto_rawDescGZIP(), []int{6}
}

func (x *AgentState) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentState) GetAgentType() AgentType {
	if x != nil {
		return x.AgentType
	}
	return AgentType_AGENT_TYPE_UNSPECIFIED
}

func (x *AgentState) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AgentState) GetCurrentTask() string {
	if x != nil {
		return x.CurrentTask
	}
	return ""
}

func (x *AgentState) GetMemory() map[string]string {
	if x != nil {
		return x.Memory
	}
	return nil
}

// Streaming
type StreamRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId    string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*StreamRequest_Chat
	//	*StreamRequest_AudioData
	Payload       isStreamRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_neuronai_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neuronai_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_neuronai_proto_rawDescGZIP(), []int{7}
}

func (x *StreamRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StreamRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StreamRequest) GetPayload() isStreamRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *StreamRequest) GetChat() *ChatRequest {
	if x != nil {
		if x, ok := x.Payload.(*StreamRequest_Chat); ok {
			return x.Chat
		}
	}
	return nil
}

func (x *StreamRequest) GetAudioData() []byte {
	if x != nil {
		if x, ok := x.Payload.(*StreamRequest_AudioData); ok {
			return x.AudioData
		}
	}
	return nil
}

type isStreamRequest_Payload interface {
	isStreamRequest_Payload()
}

type StreamRequest_Chat struct {
	Chat *ChatRequest `protobuf:"bytes,3,opt,name=chat,proto3,oneof"`
}

type StreamRequest_AudioData struct {
	AudioData []byte `protobuf:"bytes,4,opt,name=audio_data,json=audioData,proto3,oneof"`
}

func (*StreamRequest_Chat) isStreamRequest_Payload() {}

func (*StreamRequest_AudioData) isStreamRequest_Payload() {}

type StreamResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*StreamResponse_Chat
	//	*StreamResponse_AudioData
	//	*StreamResponse_SwarmUpdate
	Payload       isStreamResponse_Payload `protobuf_oneof:"payload"`
	IsHeartbeat   bool                     `protobuf:"varint,5,opt,name=is_heartbeat,json=isHeartbeat,proto3" json:"is_heartbeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamResponse) Reset() {
	*x = StreamResponse{}
	mi := &file_neuronai_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResponse) ProtoMessage() {}

func (x *StreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neuronai_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResponse.ProtoReflect.Descriptor instead.
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return file_neuronai_proto_rawDescGZIP(), []int{8}
}

func (x *StreamResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StreamResponse) GetPayload() isStreamResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *StreamResponse) GetChat() *ChatResponse {
	if x != nil {
		if x, ok := x.Payload.(*StreamResponse_Chat); ok {
			return x.Chat
		}
	}
	return nil
}

func (x *StreamResponse) GetAudioData() []byte {
	if x != nil {
		if x, ok := x.Payload.(*StreamResponse_AudioData); ok {
			return x.AudioData
		}
	}
	return nil
}

func (x *StreamResponse) GetSwarmUpdate() *SwarmState {
	if x != nil {
		if x, ok := x.Payload.(*StreamResponse_SwarmUpdate); ok {
			return x.SwarmUpdate
		}
	}
	return nil
}

func (x *StreamResponse) GetIsHeartbeat() bool {
	if x != nil {
		return x.IsHeartbeat
	}
	return false
}

type isStreamResponse_Payload interface {
	isStreamResponse_Payload()
}

type StreamResponse_Chat struct {
	Chat *ChatResponse `protobuf:"bytes,2,opt,name=chat,proto3,oneof"`
}

type StreamResponse_AudioData struct {
	AudioData []byte `protobuf:"bytes,3,opt,name=audio_data,json=audioData,proto3,oneof"`
}

type StreamResponse_SwarmUpdate struct {
	SwarmUpdate *SwarmState `protobuf:"bytes,4,opt,name=swarm_update,json=swarmUpdate,proto3,oneof"`
}

func (*StreamResponse_Chat) isStreamResponse_Payload() {}

func (*StreamResponse_AudioData) isStreamResponse_Payload() {}

func (*StreamResponse_SwarmUpdate) isStreamResponse_Payload() {}

type GetSwarmStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSwarmStateRequest) Reset() {
	*x = GetSwarmStateRequest{}
	mi := &file_neuronai_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSwarmStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSwarmStateRequest) ProtoMessage() {}

func (x *GetSwarmStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neuronai_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSwarmStateRequest.ProtoReflect.Descriptor instead.
func (*GetSwarmStateRequest) Descriptor() ([]byte, []int) {
	return file_neuronai_proto_rawDescGZIP(), []int{9}
}

func (x *GetSwarmStateRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

var File_neuronai_proto protoreflect.FileDescriptor

const file_neuronai_proto_rawDesc = "" +
	"\n" +
	"\x0eneuronai.proto\x12\bneuronai\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcf\x02\n" +
	"\vChatRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x128\n" +
	"\fmessage_type\x18\x04 \x01(\x0e2\x15.neuronai.MessageTypeR\vmessageType\x126\n" +
	"\vattachments\x18\x05 \x03(\v2\x14.neuronai.AttachmentR\vattachments\x12?\n" +
	"\bmetadata\x18\x06 \x03(\v2#.neuronai.ChatRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8a\x03\n" +
	"\fChatResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x128\n" +
	"\fmessage_type\x18\x04 \x01(\x0e2\x15.neuronai.MessageTypeR\vmessageType\x122\n" +
	"\n" +
	"agent_type\x18\x05 \x01(\x0e2\x13.neuronai.AgentTypeR\tagentType\x12,\n" +
	"\x06status\x18\x06 \x01(\x0e2\x14.neuronai.TaskStatusR\x06status\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x19\n" +
	"\bis_final\x18\b \x01(\bR\aisFinal\x121\n" +
	"\n" +
	"tool_calls\x18\t \x03(\v2\x12.neuronai.ToolCallR\ttoolCalls\"{\n" +
	"\n" +
	"Attachment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\"d\n" +
	"\bToolCall\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\targuments\x18\x03 \x01(\tR\targuments\x12\x16\n" +
	"\x06result\x18\x04 \x01(\tR\x06result\"\xaa\x03\n" +
	"\tSwarmTask\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12'\n" +
	"\x0frequired_agents\x18\x04 \x03(\tR\x0erequiredAgents\x12:\n" +
	"\acontext\x18\x05 \x03(\v2 .neuronai.SwarmTask.ContextEntryR\acontext\x12,\n" +
	"\x06status\x18\x06 \x01(\x0e2\x14.neuronai.TaskStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa3\x02\n" +
	"\n" +
	"SwarmState\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12,\n" +
	"\x06agents\x18\x02 \x03(\v2\x14.neuronai.AgentStateR\x06agents\x126\n" +
	"\fcurrent_task\x18\x03 \x01(\v2\x13.neuronai.SwarmTaskR\vcurrentTask\x12N\n" +
	"\x0eshared_context\x18\x04 \x03(\v2'.neuronai.SwarmState.SharedContextEntryR\rsharedContext\x1a@\n" +
	"\x12SharedContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8b\x02\n" +
	"\n" +
	"AgentState\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x122\n" +
	"\n" +
	"agent_type\x18\x02 \x01(\x0e2\x13.neuronai.AgentTypeR\tagentType\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12!\n" +
	"\fcurrent_task\x18\x04 \x01(\tR\vcurrentTask\x128\n" +
	"\x06memory\x18\x05 \x03(\v2 .neuronai.AgentState.MemoryEntryR\x06memory\x1a9\n" +
	"\vMemoryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa0\x01\n" +
	"\rStreamRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12+\n" +
	"\x04chat\x18\x03 \x01(\v2\x15.neuronai.ChatRequestH\x00R\x04chat\x12\x1f\n" +
	"\n" +
	"audio_data\x18\x04 \x01(\fH\x00R\taudioDataB\t\n" +
	"\apayload\"\xe7\x01\n" +
	"\x0eStreamResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12,\n" +
	"\x04chat\x18\x02 \x01(\v2\x16.neuronai.ChatResponseH\x00R\x04chat\x12\x1f\n" +
	"\n" +
	"audio_data\x18\x03 \x01(\fH\x00R\taudioData\x129\n" +
	"\fswarm_update\x18\x04 \x01(\v2\x14.neuronai.SwarmStateH\x00R\vswarmUpdate\x12!\n" +
	"\fis_heartbeat\x18\x05 \x01(\bR\visHeartbeatB\t\n" +
	"\apayload\"5\n" +
	"\x14GetSwarmStateRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId*\xb7\x01\n" +
	"\tAgentType\x12\x1a\n" +
	"\x16AGENT_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17AGENT_TYPE_ORCHESTRATOR\x10\x01\x12\x19\n" +
	"\x15AGENT_TYPE_RESEARCHER\x10\x02\x12\x15\n" +
	"\x11AGENT_TYPE_WRITER\x10\x03\x12\x13\n" +
	"\x0fAGENT_TYPE_CODE\x10\x04\x12\x14\n" +
	"\x10AGENT_TYPE_IMAGE\x10\x05\x12\x14\n" +
	"\x10AGENT_TYPE_VIDEO\x10\x06*\xc3\x01\n" +
	"\vMessageType\x12\x1c\n" +
	"\x18MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11MESSAGE_TYPE_TEXT\x10\x01\x12\x16\n" +
	"\x12MESSAGE_TYPE_IMAGE\x10\x02\x12\x16\n" +
	"\x12MESSAGE_TYPE_VIDEO\x10\x03\x12\x15\n" +
	"\x11MESSAGE_TYPE_CODE\x10\x04\x12\x1a\n" +
	"\x16MESSAGE_TYPE_TOOL_CALL\x10\x05\x12\x1c\n" +
	"\x18MESSAGE_TYPE_TOOL_RESULT\x10\x06*\xad\x01\n" +
	"\n" +
	"TaskStatus\x12\x1b\n" +
	"\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13TASK_STATUS_PENDING\x10\x01\x12\x1b\n" +
	"\x17TASK_STATUS_IN_PROGRESS\x10\x02\x12\x19\n" +
	"\x15TASK_STATUS_COMPLETED\x10\x03\x12\x16\n" +
	"\x12TASK_STATUS_FAILED\x10\x04\x12\x19\n" +
	"\x15TASK_STATUS_CANCELLED\x10\x052\xd2\x01\n" +
	"\tAIService\x12<\n" +
	"\vProcessChat\x12\x15.neuronai.ChatRequest\x1a\x16.neuronai.ChatResponse\x12F\n" +
	"\rProcessStream\x12\x17.neuronai.StreamRequest\x1a\x18.neuronai.StreamResponse(\x010\x01\x12?\n" +
	"\x10ExecuteSwarmTask\x12\x13.neuronai.SwarmTask\x1a\x14.neuronai.SwarmState0\x012\xd7\x01\n" +
	"\x11SwarmOrchestrator\x12;\n" +
	"\rRegisterAgent\x12\x14.neuronai.AgentState\x1a\x14.neuronai.AgentState\x12>\n" +
	"\x10UpdateSwarmState\x12\x14.neuronai.SwarmState\x1a\x14.neuronai.SwarmState\x12E\n" +
	"\rGetSwarmState\x12\x1e.neuronai.GetSwarmStateRequest\x1a\x14.neuronai.SwarmStateB1Z/github.com/neuronai/backend/go/internal/grpc/pbb\x06proto3"

var (
	file_neuronai_proto_rawDescOnce sync.Once
	file_neuronai_proto_rawDescData []byte
)

func file_neuronai_proto_rawDescGZIP() []byte {
	file_neuronai_proto_rawDescOnce.Do(func() {
		file_neuronai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_neuronai_proto_rawDesc), len(file_neuronai_proto_rawDesc)))
	})
	return file_neuronai_proto_rawDescData
}

var file_neuronai_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_neuronai_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_neuronai_proto_goTypes = []any{
	(AgentType)(0),                // 0: neuronai.AgentType
	(MessageType)(0),              // 1: neuronai.MessageType
	(TaskStatus)(0),               // 2: neuronai.TaskStatus
	(*ChatRequest)(nil),           // 3: neuronai.ChatRequest
	(*ChatResponse)(nil),          // 4: neuronai.ChatResponse
	(*Attachment)(nil),            // 5: neuronai.Attachment
	(*ToolCall)(nil),              // 6: neuronai.ToolCall
	(*SwarmTask)(nil),             // 7: neuronai.SwarmTask
	(*SwarmState)(nil),            // 8: neuronai.SwarmState
	(*AgentState)(nil),            // 9: neuronai.AgentState
	(*StreamRequest)(nil),         // 10: neuronai.StreamRequest
	(*StreamResponse)(nil),        // 11: neuronai.StreamResponse
	(*GetSwarmStateRequest)(nil),  // 12: neuronai.GetSwarmStateRequest
	nil,                           // 13: neuronai.ChatRequest.MetadataEntry
	nil,                           // 14: neuronai.SwarmTask.ContextEntry
	nil,                           // 15: neuronai.SwarmState.SharedContextEntry
	nil,                           // 16: neuronai.AgentState.MemoryEntry
	(*timestamppb.Timestamp)(nil), // 17: google.protobuf.Timestamp
}
var file_neuronai_proto_depIdxs = []int32{
	1,  // 0: neuronai.ChatRequest.message_type:type_name -> neuronai.MessageType
	5,  // 1: neuronai.ChatRequest.attachments:type_name -> neuronai.Attachment
	13, // 2: neuronai.ChatRequest.metadata:type_name -> neuronai.ChatRequest.MetadataEntry
	1,  // 3: neuronai.ChatResponse.message_type:type_name -> neuronai.MessageType
	0,  // 4: neuronai.ChatResponse.agent_type:type_name -> neuronai.AgentType
	2,  // 5: neuronai.ChatResponse.status:type_name -> neuronai.TaskStatus
	17, // 6: neuronai.ChatResponse.timestamp:type_name -> google.protobuf.Timestamp
	6,  // 7: neuronai.ChatResponse.tool_calls:type_name -> neuronai.ToolCall
	14, // 8: neuronai.SwarmTask.context:type_name -> neuronai.SwarmTask.ContextEntry
	2,  // 9: neuronai.SwarmTask.status:type_name -> neuronai.TaskStatus
	17, // 10: neuronai.SwarmTask.created_at:type_name -> google.protobuf.Timestamp
	17, // 11: neuronai.SwarmTask.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 12: neuronai.SwarmState.agents:type_name -> neuronai.AgentState
	7,  // 13: neuronai.SwarmState.current_task:type_name -> neuronai.SwarmTask
	15, // 14: neuronai.SwarmState.shared_context:type_name -> neuronai.SwarmState.SharedContextEntry
	0,  // 15: neuronai.AgentState.agent_type:type_name -> neuronai.AgentType
	16, // 16: neuronai.AgentState.memory:type_name -> neuronai.AgentState.MemoryEntry
	3,  // 17: neuronai.StreamRequest.chat:type_name -> neuronai.ChatRequest
	4,  // 18: neuronai.StreamResponse.chat:type_name -> neuronai.ChatResponse
	8,  // 19: neuronai.StreamResponse.swarm_update:type_name -> neuronai.SwarmState
	3,  // 20: neuronai.AIService.ProcessChat:input_type -> neuronai.ChatRequest
	10, // 21: neuronai.AIService.ProcessStream:input_type -> neuronai.StreamRequest
	7,  // 22: neuronai.AIService.ExecuteSwarmTask:input_type -> neuronai.SwarmTask
	9,  // 23: neuronai.SwarmOrchestrator.RegisterAgent:input_type -> neuronai.AgentState
	8,  // 24: neuronai.SwarmOrchestrator.UpdateSwarmState:input_type -> neuronai.SwarmState
	12, // 25: neuronai.SwarmOrchestrator.GetSwarmState:input_type -> neuronai.GetSwarmStateRequest
	4,  // 26: neuronai.AIService.ProcessChat:output_type -> neuronai.ChatResponse
	11, // 27: neuronai.AIService.ProcessStream:output_type -> neuronai.StreamResponse
	8,  // 28: neuronai.AIService.ExecuteSwarmTask:output_type -> neuronai.SwarmState
	9,  // 29: neuronai.SwarmOrchestrator.RegisterAgent:output_type -> neuronai.AgentState
	8,  // 30: neuronai.SwarmOrchestrator.UpdateSwarmState:output_type -> neuronai.SwarmState
	8,  // 31: neuronai.SwarmOrchestrator.GetSwarmState:output_type -> neuronai.SwarmState
	26, // [26:32] is the sub-list for method output_type
	20, // [20:26] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_neuronai_proto_init() }
func file_neuronai_proto_init() {
	if File_neuronai_proto != nil {
		return
	}
	file_neuronai_proto_msgTypes[7].OneofWrappers = []any{
		(*StreamRequest_Chat)(nil),
		(*StreamRequest_AudioData)(nil),
	}
	file_neuronai_proto_msgTypes[8].OneofWrappers = []any{
		(*StreamResponse_Chat)(nil),
		(*StreamResponse_AudioData)(nil),
		(*StreamResponse_SwarmUpdate)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_neuronai_proto_rawDesc), len(file_neuronai_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_neuronai_proto_goTypes,
		DependencyIndexes: file_neuronai_proto_depIdxs,
		EnumInfos:         file_neuronai_proto_enumTypes,
		MessageInfos:      file_neuronai_proto_msgTypes,
	}.Build()
	File_neuronai_proto = out.File
	file_neuronai_proto_goTypes = nil
	file_neuronai_proto_depIdxs = nil
}
